use_frameworks!

platform :ios, '8.0'

target 'DBManagerThaiThit_Example' do
  pod 'DBManagerThaiThit', :path => '../'

  target 'DBManagerThaiThit_Tests' do
    inherit! :search_paths

    
  end
end
